edition = "2021"
unstable_features = true
# Unstable
comment_width = 80
condense_wildcard_suffixes = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = false
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
