#!/usr/bin/env bash
set -euo pipefail
if command -v nix &>/dev/null; then
	nix develop .#msrv --command cargo check
fi
if command -v cargo &>/dev/null; then
	if command -v cargo-clippy &>/dev/null; then
		cargo clippy
	else
		cargo check
	fi
	cargo test
fi
